[package]
name = "polygon"
version = "0.1.0"
edition = "2024"
description = "Rust client library for polygon.io"
license = "MIT"
repository = "https://github.com/inboard-ai/polygon"

[dependencies]
reqwest = { version = "0.12", optional = true, features = ["json"] }
dotenvy = { version = "0.15", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = ["reqwest", "dotenvy"]
reqwest = ["dep:reqwest"]
dotenvy = ["dep:dotenvy"]
